### ISSUE TITLE
RedMi K30, not permission read any file. / 给予授权后，仍无法读取任何文件

### ISSUE THREAD

**Issue by uiosun** [Anxcye/anx-reader#1]
机型：红米 K30
是否请求并给与文件权限：是
描述：
能看到所有目录，但无法获得任何“最近文件”，且切换到存在 txt / pdf 的文件目录，所有文件显示灰色底色，无法点击。

**Comment by Anxcye** [comment]
非常抱歉，安读目前仅支持 epub 文件，目前您可以手动将文件转换为 epub 后导入，我们将尽快支持其他类型的文件。
