### ISSUE TITLE
语音朗读！语音朗读！语音朗读！跪求

### ISSUE THREAD

**Issue by qjczzsary** [Anxcye/anx-reader#11]
语音朗读！语音朗读！语音朗读！跪求了
跪了跪了跪了，一直找一款可以WebDAV同步，有语音朗读插件的，一直没找着
跪求作者安排上

**Comment by Anxcye** [comment]
会添加的，目前计划是通过 TTS 支持语音朗读！

**Comment by qjczzsary** [comment]
可以的可以的，老板自行考虑，百度的、讯飞的语音插件可以不，这俩比较拟真，不知道收不收费，老板自行安排，能有个响就已经很好了，因为习惯走路工作啥的，听小说之类的了
另外对txt的支持挺需要的，我看已经有别人提了，大部分离线小说都是txt格式
