### ISSUE TITLE
HelloGitHub 徽章计划

### ISSUE THREAD

**Issue by 521xueweihan** [Anxcye/anx-reader#17]
🎉 恭喜！您的[项目](https://hellogithub.com/repository/819a2b3050204451bed552a8812114e5)已被 HelloGitHub 社区收录和推荐，现邀请您加入 HelloGitHub 徽章计划。加入后，您将获得以下特权：

- 社区认可: 徽章代表你的项目已通过 HelloGitHub 社区的严格筛选，并获得推荐。
- 提高曝光: 佩戴徽章后，你的项目将获得更多推荐流量，吸引更多用户和贡献者。
- 增强互动: 用户可通过徽章快速了解项目，并与之互动（点赞、评论、收藏）。
- 收集反馈: 获取广大用户的真实反馈，持续优化你的项目。
- 特殊标识: 认证后，你的评论将有显著标识，并获得置顶优先权。

📌 [立即点击](https://hellogithub.com/repository/819a2b3050204451bed552a8812114e5/embed) 完成徽章佩戴，加入 HelloGitHub 徽章计划，让你的开源项目绽放更耀眼的光彩。

---

**HelloGitHub**，一个专注于发现、分享、推广开源项目的社区。自 2016 年创立以来，从每月一更的月刊发展到今天，已经成为一个拥有超过 **1 万** 用户的充满活力的开源社区。我们的足迹遍布多个内容平台，并获得了全网 **50 万** 粉丝的信赖与支持。

**Comment by Anxcye** [comment]
感谢推荐，已提交认证。

**Comment by 521xueweihan** [comment]
@Anxcye 感谢您的认领，我看您也是倾向于小徽章，也有很多开源作者向我反馈希望出小徽章，我后面开发完小徽章再来找您佩戴吧。我不想因为徽章影响贵项目的整体排版，这是我不希望看到的。

**Comment by Anxcye** [comment]
好的！

**Comment by 521xueweihan** [comment]
@Anxcye 您好，小徽章功能已上线，可通过上面的认领地址进行认领和佩戴。

<img width="693" alt="截屏2024-07-04 16 00 22" src="https://github.com/Anxcye/anx-reader/assets/8255800/2bdbd20e-f6ea-4900-9366-737672d38a74">

**Comment by Anxcye** [comment]
好欸！已提交认领

**Comment by 521xueweihan** [comment]
@Anxcye 感谢您的认领和支持，anx-reader 已全站置顶：

<img width="777" alt="image" src="https://github.com/Anxcye/anx-reader/assets/8255800/121cdfa3-eba1-4011-aa5d-55a99ff35603">

**Comment by Anxcye** [comment]
感谢推荐！🎉

**Comment by Anxcye** [comment]
Hi, 我的账户此前被标记了一段时间，目前已经解除，但是似乎点击README的hello github徽章无法连接到hello github网站了，提示404，如何恢复呢？

**Comment by 521xueweihan** [comment]
@Anxcye 感谢您的反馈，让我发现这个问题（可能是我的爬虫程序导致误删）。我已恢复贵项目的展示和收录，后续我将持续观察，杜绝此类事件的发生。

**Comment by Anxcye** [comment]
感谢，在账户被标记期间这个仓库无法被公开访问，访问会提示404，同时访问账号也会提示404，或许这样就被程序自动识别为删库了
