### ISSUE TITLE
几个疑惑

### ISSUE THREAD

**Issue by zyusuixin** [Anxcye/anx-reader#19]
①划线功能:使用了划线无法取消，比如我不小心划了几个字，我想取消，但取消不了。

②webdav:我是nextcloud的webdav，我卸载软件重新安装，恢复备份之后没有书的封面，并且点进去只有背景，没有字，我在nextcloud的同步文件也没有找到书籍。

③划线功能左边两个图标，一个是U一个是手电筒，不知道这两个图标有什么作用，我点击没有反应。

**Comment by Anxcye** [comment]
> ①划线功能:使用了划线无法取消，比如我不小心划了几个字，我想取消，但取消不了。

这个确实有些问题，需要进一步的修改。

> ②webdav:我是nextcloud的webdav，我卸载软件重新安装，恢复备份之后没有书的封面，并且点进去只有背景，没有字，

可能是卸载软件前还没有完成同步，封面、书籍文件等还没有上传成功。

> 我在 nextcloud 的同步文件也没有找到书籍。

数据保存在 WebDAV 盘的根目录下的 `anx\`文件夹下，是否有这个文件夹呢？里面有无数据呢？

> ③划线功能左边两个图标，一个是U一个是手电筒，不知道这两个图标有什么作用，我点击没有反应。

这两个图标含义确实有些混淆，会找更明确的图标替换。

这是在选择划线的样式，下划线和高亮。先点这两个图标选择划线样式（会默认记录上一次选择的样式，不更改样式时可忽略这一步），然后点颜色确定颜色。

**Comment by Anxcye** [comment]
2 缺少进一步信息
1、3已解决
