### ISSUE TITLE
English README

### ISSUE THREAD

**Issue by killeik** [Anxcye/anx-reader#20]
I like your app and I want to spread it all over the world!

Your application already supports English language.
I will be glad if you add English version of README.md.

If you don't want to replace the current README.md, you can make the English version a link in the header, like other projects do. 

For example: 
https://github.com/hiddify/hiddify-next

**Comment by Anxcye** [comment]
We are delighted to hear that you've enjoyed using this application and appreciate your eagerness to share it with a global audience. Your feedback means a lot to us, and we thank you for your support and enthusiasm.

Now, the README has been successfully updated to English, making this project more accessible to a wider community. This change will help spread the word about the app and potentially attract new contributors and users from around the world.

**Comment by killeik** [comment]
Thank you!
I will try to spread the application among people
