### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by dongbao66** [Anxcye/anx-reader#22]
1.主界面的笔记无法删除 阅读时不知道功能乱添加了十几条

2.阅读目录需要点两下才会打开，点一次没反应

3.希望添加仿真翻页

4.每一章节末尾翻页过渡不自然，会闪一下

**Comment by Anxcye** [comment]
关于1、4条可以试试最新版本（v1.1.4），是否能解决呢？

>2.阅读目录需要点两下才会打开，点一次没反应

确实存在这个问题，正在修。

>3.希望添加仿真翻页

好的，但这部分比较复杂，会尽快

**Comment by dongbao66** [comment]
用的就是最新版

**Comment by Anxcye** [comment]
哦，是我理解错了，是指在“笔记”界面无法删除笔记吗？这个确实，会添加相关功能~

**Comment by dongbao66** [comment]
是的 你理解错了

**Comment by Anxcye** [comment]
除仿真翻页外已解决，已记下需求，此issue将关闭
