### ISSUE TITLE
[BUG]行间距问题

### ISSUE THREAD

**Issue by superjjx** [Anxcye/anx-reader#24]
作者大大好！
我在设置中改变行间距大小时，阅读界面的行间距没有变化，受到影响的是弹注文本中的行间距。
软件版本：1.1.5
安卓版本：11

**Comment by Anxcye** [comment]
是哪本书呢？是否方便分享下书籍文件呢？

**Comment by superjjx** [comment]
> 是哪本书呢？是否方便分享下书籍文件呢？

书籍已经发至你的邮箱，请注意查收。

**Comment by superjjx** [comment]
[司马辽太郎经典作品集（共9册）.zip](https://github.com/user-attachments/files/16580604/9.zip)
发的邮件总是退信

**Comment by Anxcye** [comment]
好的，果然在邮箱中没有看到，这样收到了

**Comment by Anxcye** [comment]
已解决
