### ISSUE TITLE
(BUG): Notes/Highlights

### ISSUE THREAD

**Issue by scientiac** [Anxcye/anx-reader#25]
I am not able to delete the notes, upon trying to reselect the same word and change colors/underline it makes multiple notes for the same text instead of changing it.

![Screenshot_20240812-183229](https://github.com/user-attachments/assets/894977d7-0b7b-4847-b030-971ba618d7c9)

**Comment by Anxcye** [comment]
Currently, it's not possible to delete notes on this interface (this feature will be supported in the future). To delete a note, you need to open the book, find the note, and click on it. A menu will pop up where you can delete the note.

> Changing colors/underline creates multiple notes for the same text instead of modifying the existing one.

You don't need to long-press and select the text again to change the color. You can simply click on the note and change it from the pop-up menu.

However, it appears that there is indeed a logical issue here. It shouldn't add the same text to the note list multiple times. I'll fix it soon.

**Comment by Anxcye** [comment]
Now that the problem has been solved, I will close this issue.
