### ISSUE TITLE
Desktop request

### ISSUE THREAD

**Issue by ybbluesky** [Anxcye/anx-reader#26]
有电脑版吗？希望能出电脑版

**Comment by Anxcye** [comment]
还没有，目前正在等待 [此 issue ](https://github.com/pichillilorenzo/flutter_inappwebview/issues/460)解决。

**Comment by Ph0enix007** [comment]
希望能早点出个Linux版本

**Comment by Anxcye** [comment]
目前正在等待 [inappwebview](https://pub.dev/packages/flutter_inappwebview) 支持Windows和Linux，这个插件目前仅支持 [Android](https://pub.dev/packages?q=platform%3Aandroid) [iOS](https://pub.dev/packages?q=platform%3Aios) [macOS](https://pub.dev/packages?q=platform%3Amacos) [web](https://pub.dev/packages?q=platform%3Aweb)

**Comment by Anxcye** [comment]
windows已支持

**Comment by czcn** [comment]
win11打开书本闪退，用win7兼容不闪退，但打开书本只有书名没有内容。

**Comment by Anxcye** [comment]
> 打开后只有书名没有内容

能否提供截图和书籍文件呢

**Comment by czcn** [comment]
1.2.2有bug, 1.2.1可以用

**Comment by Anxcye** [comment]
此问题已经在最新版本中解决。我将关闭此 issue。
