### ISSUE TITLE
点击书籍后显示“网页无法打开”

### ISSUE THREAD

**Issue by aldinwilson** [Anxcye/anx-reader#28]
![1723641841842](https://github.com/user-attachments/assets/6d3d4b8b-3849-47cc-a89f-68f171ef7bf5)

**Comment by Anxcye** [comment]
打开软件，重现该问题后，前往设置>>更多设置>>高级>>日志 向下滑动，可以看到下面有一条类似
```
INFO^*^ 2024-08-09 17:51:22.573971^*^ [Webview: Mozilla/5.0 (Linux; Android 13; *** Build/TKQ1.220829.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.25 Mobile Safari/537.36]:null
```
的日志，能把那一条日志发在这里吗？

**Comment by aldinwilson** [comment]
> 打开软件，重现该问题后，前往设置>>更多设置>>高级>>日志 向下滑动，可以看到下面有一条类似
> 
> ```
> INFO^*^ 2024-08-09 17:51:22.573971^*^ [Webview: Mozilla/5.0 (Linux; Android 13; *** Build/TKQ1.220829.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.25 Mobile Safari/537.36]:null
> ```
> 
> 的日志，能把那一条日志发在这里吗？

INFO^*^ 2024-08-14 22:04:16.543141^*^ [Webview: Mozilla/5.0 (Linux; Android 11; Redmi K20 Pro Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36]:null

**Comment by Anxcye** [comment]
看起来是手机webview版本很低（目前你的版本是83.0.4103.106），可以从Google play或其他地方更新webview

**Comment by aldinwilson** [comment]
> 看起来是手机webview版本很低（目前你的版本是83.0.4103.106），可以从Google play或其他地方更新webview

已解决，谢谢大佬！

**Comment by Anxcye** [comment]
🎉

**Comment by aldinwilson** [comment]
> 🎉

想问下大佬，笔记是不是划线了就无法删除了？而且我发现个别epub的书调格式有问题（比如字体大小，没反应，调大了数值，字还是那么大）

**Comment by Anxcye** [comment]
划线目前只能打开书，从那里删除，之后会在划线列表添加删除功能。
