### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by Maybeyok** [Anxcye/anx-reader#31]
1.epub格式的书籍内置的图片没法打开。
2.翻页时页面会出现抖动。https://github.com/user-attachments/assets/62e5062f-e13b-492d-8680-9c1b5f5daa59

https://github.com/user-attachments/assets/ca615fea-eeb6-4717-ab4d-60e3ac53cc9d

（能打开图片软件的是多看）![Screenshot_2024-09-03-16-18-14-607_com.anxcye.anx_reader-edit.jpg](https://github.com/user-attachments/assets/78e6804a-53ba-4563-8ac0-9018a2d24dac)

（圈出来的部分会出现抖动）
3.阅读epub格式的书籍时有点卡顿，翻页不流畅，页面会出现抖动。

**Comment by Anxcye** [comment]
是的，书籍内置图片暂时不支持打开，会尽快支持
我没有遇到抖动的问题，方便的话能否提供录屏？
翻页卡顿会持续优化

**Comment by Anxcye** [comment]
明白了
