### ISSUE TITLE
[BUG]导入失败。两种都报错导入直接闪退

### ISSUE THREAD

**Issue by Atlas52306** [Anxcye/anx-reader#32]
日志没有发现error的报错只有几个info，日志文件不能创建和本地35149端口的报错，错误原因为null希望作者大大能处理下。
设备为口袋阅一代 墨水屏设备，也希望能出一个墨水屏版本的，辛苦啦

**Comment by Anxcye** [comment]
可以上传下日志文件吗？另外可以参考https://github.com/Anxcye/anx-reader/issues/28#issuecomment-2288756998 检查下webview版本

**Comment by Atlas52306** [comment]
> 可以上传下日志文件吗？ 另外可以参考[#28 (comment)](https://github.com/Anxcye/anx-reader/issues/28#issuecomment-2288756998)检查下webview版本

作者你好，webview版本确实是非常低，浏览器现在我智能使用X5内核的浏览器，别的使用系统内核的浏览器比如via，x浏览器无法使用
以下是日志文件，因导出日志也闪退所以智能拍照了，见谅，可能顺序有点不对
![c5e6661b41ed121c3662e877268896b](https://github.com/user-attachments/assets/9659955c-de8d-4825-b42b-9c9850f4d7d2)
![167282e19bb5d521fe89ed92a7d2f5a](https://github.com/user-attachments/assets/df5c11f5-ff81-4315-800d-17daab0a7b0a)
![6fba18f2522c222aa82b7314ba39325](https://github.com/user-attachments/assets/9e0b0373-b74f-40f8-b9c8-b15db0cdb1d5)
![18ccc4d0b360877462371e9fca267a5](https://github.com/user-attachments/assets/0a6eca89-c460-4d2b-96ef-5c8054520d6f)
![479f0503df619f10ce7ddf1c01bd73e](https://github.com/user-attachments/assets/08a7133c-baa0-4127-b473-c7fcee2492f2)

![d6da0f9a25a6b48f83eee2e1731fc31](https://github.com/user-attachments/assets/af75491a-d8ff-46b1-8a44-95d469c16af0)
![a8942dbe54a7d44a4c7f14809d7657f](https://github.com/user-attachments/assets/fb60f943-9aa7-4f6c-b53d-75905ad75359)
![6aa65b00e5f81bba14295c247eb8c97](https://github.com/user-attachments/assets/c56d549c-1825-4f7d-9705-847cf2483d8d)

**Comment by Atlas52306** [comment]
补充：若需要测试，可联系我

**Comment by Atlas52306** [comment]
> 可以上传下日志文件吗？另外可以参考[#28 (comment)](https://github.com/Anxcye/anx-reader/issues/28#issuecomment-2288756998) 检查下webview版本


补充：上面上传的是全部日志并没有webview的信息
若需要测试，可联系我

**Comment by Anxcye** [comment]
是一点击右上角的加号就会闪退吗？

**Comment by Atlas52306** [comment]
> 是一点击右上角的加号就会闪退吗？

不是，点了加号以后，不是跳出两种方式嘛，然后在选择了一本epub格式的书以后在最后选择添加才会闪退

**Comment by Anxcye** [comment]
查了一下，很有可能是webview版本过低导致的，在导入图书时也需要应用webview进行解析，能否尝试更新下呢？

**Comment by Atlas52306** [comment]
> 查了一下，很有可能是webview版本过低导致的，在导入图书时也需要应用webview进行解析，能否尝试更新下呢？

更新不了，厂家已经停止服务了，这就有点难办
