### ISSUE TITLE
是我对epub的理解有问题吗☝🏻️🤓

### ISSUE THREAD

**Issue by CS-XiaoZhao** [Anxcye/anx-reader#39]
![Screenshot_2024-11-08-19-15-06-057_bin.mt.plus.jpg](https://github.com/user-attachments/assets/bd6ce9d3-c698-4703-a5c9-74fd322aae54)

![Screenshot_2024-11-08-19-15-17-893_com.anxcye.anx_reader.jpg](https://github.com/user-attachments/assets/ff9f50f4-45dc-4689-a2c6-f422aec8db47)

明明是在z-library下载的epub文件怎么导入就不可以了呢？

**Comment by Anxcye** [comment]
点击右上角导入键后跳转到的文件选择器是 安卓系统自带的 还是 自己安装的 呢？

如果是安卓默认的，点击左上角，打开下面这样的抽屉，从箭头指示的地方打开文件能否导入？
<img width="251" alt="image" src="https://github.com/user-attachments/assets/e15f7f2b-5d51-48c6-b424-284d1fcae67c">

如果可以，这可能是存储访问框架的一个问题，从你的截图可以看到安读没有读到文件的扩展名`epub`

**Comment by CS-XiaoZhao** [comment]
成功导入，肥肠感谢
