### ISSUE TITLE
[bug]导入电子书后打开只显示一个封面，不能往后翻。

### ISSUE THREAD

**Issue by btskc** [Anxcye/anx-reader#4]
如题，导入的电子书是epub2的。格式应该没问题吧？

**Comment by Anxcye** [comment]
点击左右两侧能否翻页呢？目前翻页方式为点击左右两侧进行翻页。

**Comment by btskc** [comment]
试了一下可以了，不过左右点击部分的面积有点小。另外也看不见左右两侧有翻页按钮，不知道是不是跟我设置有关系。能不能改成左右滑动翻页？

**Comment by Anxcye** [comment]
好的，会提供更多翻页方式
