### ISSUE TITLE
[BUG] 严重问题！导入书籍会直接删除书籍源文件！

### ISSUE THREAD

**Issue by ljporljp** [Anxcye/anx-reader#42]
我因此丢失了两本书的源文件！！！这个是流氓病毒行为！！！建议不要下载使用！！！

**Comment by ljporljp** [comment]
是pc版本

**Comment by Anxcye** [comment]
如果已经导入成功，可以查看C:\Users\{username}\AppData\Roaming\com.anxcye\anx_reader\file 或C:\Users\{username}\AppData\Local\com.anxcye\anx_reader\file找到导入的图书。

这确实是一个严重的问题，使用的文件选择库在windows端逻辑不同。很快将会修复。

**Comment by Anxcye** [comment]
已发布新版已解决
