### ISSUE TITLE
[BUG]带有中文大括号的书名文件无法正确导入

### ISSUE THREAD

**Issue by sizelborgia** [Anxcye/anx-reader#44]
![SmartSelect_20241119_183137_Anx Reader.jpg](https://github.com/user-attachments/assets/dd5d9a44-ae69-4798-8da3-ad1e2568fe5a)
经过对比测试，有空格无大括号的文件可以导入，而有大括号的却无法导入，不知道是不是我个人的问题，版本是最新发布的1.2.0
不知道调整起来是否费功夫，但是有很多书本身带括号，辛苦作者了

**Comment by Anxcye** [comment]
是安卓平台吗，安卓可能是这个问题 https://github.com/Anxcye/anx-reader/issues/39#issuecomment-2467115908

从 下载、最近 之类的快捷访问来选择文件读不到扩展名。

**Comment by sizelborgia** [comment]
> 是安卓平台吗，安卓可能是这个问题 https://github.com/Anxcye/anx-reader/issues/39#issuecomment-2467115908
> 
> 从 下载、最近 之类的快捷访问来选择文件读不到扩展名。

了解了，确实如此
