### ISSUE TITLE
[BUG]阅读进度丢失问题

### ISSUE THREAD

**Issue by superjjx** [Anxcye/anx-reader#45]
作者大大好！
昨晚到今天出现了两次阅读进度丢失的问题（偶尔出现），操作过程如下：
因为没有“退出”按钮，所以每次退出都是用手势划动结束进程，正常情况下，划掉进程时，动画应该是干净利落，但是两次出问题时都是在划动时动画出现了延迟（像慢放一般）。不知道你那边能不能复现。
p.s.也许与特定手机型号有关？（redmi k20,andriod 11)

**Comment by superjjx** [comment]
旧版本未出现此情况。

**Comment by Anxcye** [comment]
现在更新了进度的记录频率，应该不再会出现进度丢失的问题，我将关闭此 issue，有问题可重新打开。
