### ISSUE TITLE
[BUG]为什么导入书都导入不了呢？

### ISSUE THREAD

**Issue by wuya1019** [Anxcye/anx-reader#46]
<img width="949" alt="11111" src="https://github.com/user-attachments/assets/3a9d85a3-8223-405a-a2dd-c27a07748c5a">

**Comment by Anxcye** [comment]
什么平台呢？系统版本是多少？windows10可能需要安装webview2. https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by weiliseco** [comment]
> 什么平台呢？系统版本是多少？windows10可能需要安装webview2. https://go.microsoft.com/fwlink/p/?LinkId=2124703什么平台呢？ 系统版本是多少？ windows10可能需要安装webview2. https://go.microsoft.com/fwlink/p/?LinkId=2124703

遇到同样问题，windows 10版本无法导入书籍，有安装过webview2.

**Comment by weiliseco** [comment]
![image](https://github.com/user-attachments/assets/f0ac2bc4-33d9-4b8a-bff5-a88ba929402f)

**Comment by poppop0911** [comment]
android 遇到同样导入不了的问题

**Comment by Anxcye** [comment]
> android 遇到同样导入不了的问题

安卓可能是 https://github.com/Anxcye/anx-reader/issues/39#issuecomment-2467115908

Win10我可能需要进一步测试下，我目前在使用Win11没有问题

**Comment by oyyuyu** [comment]
导入不了，是一定需要联网的，还是支持单机的？

**Comment by Anxcye** [comment]
问题已经排查解决。

这个问题是新安装1.2.1时会出现的问题。从旧版本更新到1.2.1时不会遇到，所以我没有测试到这个问题。

需要卸载1.2.1版本，然后删除 `C:\Users\{USERNAME}\AppData\Roaming\com.anxcye` 文件夹。

**Comment by weiliseco** [comment]
1.2.2（1.2.2 2024-12-02）版本在win10下还是无法导入书籍 mobi 及epub\txt格式都不行
![image](https://github.com/user-attachments/assets/cfa0ae4a-429c-4d57-8c75-6cf2e7059a64)

**Comment by Anxcye** [comment]
最新版本应该已经解决此问题，我将关闭此 issue，有问题可重新打开。
