### ISSUE TITLE
docker 部署

### ISSUE THREAD

**Issue by fengwang** [Anxcye/anx-reader#5]
是否可以把  web 端部署到服务器上去，加上本地持久化存储之后就有了上传下载各端同步功能。

**Comment by Anxcye** [comment]
好主意，另外可能还会提供WebDAV的同步。

**Comment by kokojacket** [comment]
wow已经可以docker部署了吗？

**Comment by Anxcye** [comment]
还没有docker部署，目前是通过 WebDAV 同步

**Comment by kokojacket** [comment]
> 还没有docker部署，目前是通过 WebDAV 同步

请问后面会考虑打包镜像docker部署吗

**Comment by kokojacket** [comment]
> 还没有docker部署，目前是通过 WebDAV 同步

请问后面会考虑打包镜像docker部署吗

**Comment by Anxcye** [comment]
大概会有，不过可能会比较晚一点了。
