### ISSUE TITLE
[Bug]: 导入图书后打开闪退

### ISSUE THREAD

**Issue by liangpixiao** [Anxcye/anx-reader#55]
### Prerequisites|前提条件

- [X] I have checked the [troubleshooting](https://github.com/Anxcye/anx-reader/blob/develop/docs/troubleshooting.md)|我已经查看过[故障排除](https://github.com/Anxcye/anx-reader/blob/develop/docs/troubleshooting.md)
- [X] I have searched for similar issues and did not find any|我已经搜索过没有相同的问题

### Describe the bug|描述问题

导入图书后，打开先卡死为空白页面，然后闪退，安装版本和绿色版本都存在这个问题，我的系统是Windows 10 专业版，希望大大解决

### To reproduce|重现步骤

1. Go to '...' | 前往...
2. Click on '...' | 点击...
3. Scroll down to '...' | 向下滚动到...
4. See error | 看到错误

### Expected behavior|预期行为

需要我做什么改变能正常的享用您的软件

### Platform (please complete the following information)|平台（请填写以下信息）

- Platform: | 平台：Windows 10 专业版
  [e.g. Android]
- OS: | 操作系统：
  [e.g. Android13(MIUI14)]
- AnxReader Version: | 安读版本：
  [e.g. 1.2.0+2033]
- Device: | 设备：
  [e.g. Xiaomi 13]

**Comment by Anxcye** [comment]
新版本应该已经解决，我将关闭此 issue，有问题可重新打开。
