### ISSUE TITLE
[Bug]: 在win10上安装无法启动运行

### ISSUE THREAD

**Issue by axiyd** [Anxcye/anx-reader#57]
### Prerequisites|前提条件

- [X] I have checked the [troubleshooting](https://github.com/Anxcye/anx-reader/blob/develop/docs/troubleshooting.md)|我已经查看过[故障排除](https://github.com/Anxcye/anx-reader/blob/develop/docs/troubleshooting.md)
- [X] I have searched for similar issues and did not find any|我已经搜索过没有相同的问题

### Describe the bug|描述问题

在win10上安装无法启动运行

### To reproduce|重现步骤

1. Go to '...' | 前往...
2. Click on '...' | 点击...
3. Scroll down to '...' | 向下滚动到...
4. See error | 看到错误

### Expected behavior|预期行为

期待建立qq群，尽快修复该bug

### Platform (please complete the following information)|平台（请填写以下信息）

Win10

**Comment by axiyd** [comment]
无

**Comment by Anxcye** [comment]
新版本应该已经解决，我将关闭此 issue，有问题可重新打开。
