### ISSUE TITLE
安卓app导入部分epub书籍没反应

### ISSUE THREAD

**Issue by amu263** [Anxcye/anx-reader#6]
书名：华丽人生，作者伊坂幸太郎

**Comment by amu263** [comment]
![Uploading 1714192439519.png…]()

**Comment by amu263** [comment]
![1714192439519](https://github.com/Anxcye/anx-reader/assets/123864680/f16def86-e803-4ad3-8e2a-c830270b9ae7)

**Comment by Anxcye** [comment]
原因可能是 epub 图书标题太长，将 epub 文件以 zip 的方式解压后查看 `content.opf` 文件，或许可以发现该图书标题如下：

> 华丽人生【百万畅销作家伊坂幸太郎全新杰作，五度入围直木奖，比肩村上春树、东野圭吾。获奖无数频频被搬上荧幕，原著改编电影由堺雅人倾情出演！一场仿佛行走于莫比乌斯环的阅读体验 】

可以尝试修改 `content.opf` 中的内容查看是否能够导入。
该问题已修复，将在下个版本中发布！
