### ISSUE TITLE
Theme Editing

### ISSUE THREAD

**Issue by rahaaatul** [Anxcye/anx-reader#7]
# Description
1. Let us select and edit numbers without having to guess the color in the color box.
![image](https://github.com/Anxcye/anx-reader/assets/86149861/9fcd0472-5b71-41c8-b6c1-5350c5a3ece5)

2. Add HEX as a color option.

**Comment by Anxcye** [comment]
Ah, that seems to be a bug in the [color picker](https://github.com/mchome/flutter_colorpicker). Is there any change when rotating the device to landscape/portrait? What is the device resolution? In fact, the interface should look like this:
![image](https://github.com/Anxcye/anx-reader/assets/91717732/73b4d9cc-8d9e-4501-9838-b45a6b8c7233)

**Comment by rahaaatul** [comment]
> Ah, that seems to be a bug in the [color picker](https://github.com/mchome/flutter_colorpicker). Is there any change when rotating the device to landscape/portrait? What is the device resolution?

Sorry I should have included the device information.

I was using Latest Nox emulator, Android 9. The resolution is 1366x768.

**Comment by Anxcye** [comment]
I can't reproduce the problem, but there is now a native Windows version.  Maybe the emulator is no longer needed.
