### ISSUE TITLE
Are you considering a more affordable syncing method - S3?

### ISSUE THREAD

**Issue by Benjamin-Watson0** [Anxcye/anx-reader#8]
Could we add S3 syncing? It's more affordable. WebDAV isn't great because there aren't good cloud storage options, and setting up our own isn't worth it.
We could even consider adding Ali Cloud Disk, which has recently become quite popular.

我们能否添加S3同步功能？它更加经济。WebDAV不太好，因为它没有好的网盘选择，而我们设置自己的自托管webdav并不值得。
我们甚至可以考虑添加阿里云盘，最近它变得相当受欢迎。

**Comment by Anxcye** [comment]
The requirement has been documented, but S3 sync probably won't be added anytime soon. As for WebDAV network disk, you can try [jianguoyun（坚果云）](https://www.jianguoyun.com/)

<details>
<summary>中文</summary>

需求已记录，但短时间内大概不会添加 S3 同步。对于 WebDAV 网盘，可以尝试 [坚果云](https://www.jianguoyun.com/)。

</details>
