### ISSUE TITLE
翻页能不能加一个过渡的动画效果

### ISSUE THREAD

**Issue by 11nk** [Anxcye/anx-reader#9]
如题如述，目前翻页感觉有点僵。

**Comment by Anxcye** [comment]
会添加，但这个功能有些复杂，会尽快

**Comment by BingCoke** [comment]
> 会添加，但这个功能有些复杂，会尽快

请问有进展吗,最近也在使用epubjs库,看了一下源代码确实比较麻烦,库用的是column布局进行分割,如果能获取每一页的html进行单独渲染就好了..不知道作者是否有什么想法可以探讨一下

**Comment by Anxcye** [comment]
有了一些进展了，目前是通过 `scrollLeft` 将分割成多个 `column`的页面左右移动，是最简单的一个过渡动画了。不过目前滑动还有些卡顿。

主要是通过这行代码：
https://github.com/Anxcye/anx-reader/blob/edadf9ddbff4ab7a9e358b5cfd2a32d7ac603711/lib/utils/generate_index_html.dart#L249C11-L249C104

另外，还需要禁止原epubjs库中 `rendition.next()` 的移动，修改了这里：
https://github.com/Anxcye/anx-reader/blob/edadf9ddbff4ab7a9e358b5cfd2a32d7ac603711/assets/js/epub.js#L4513C1-L4514C35

**Comment by BingCoke** [comment]
只能这样了，其实我还想过渲染三个rendition互相叠加，虽然有点丑陋，但是性能损失其实并不多，毕竟只是一些文本

**Comment by BingCoke** [comment]
> 如题如述，目前翻页感觉有点僵。

可以尝试一下将本页内容进行截图,然后翻动的时候直接跳转到上/下一页,然后对截图进行页面滚动.不过html-to-image库对于iframe的图片截图有问题. 还在研究,不过感觉这个思路可行

**Comment by Anxcye** [comment]
新版本（v1.1.3）已添加一种滑动翻页动画，此 issue 将被关闭，有任何问题可重新打开。

**Comment by 11nk** [comment]
翻页的体验 感觉不是很统一，有的小说翻页会有卡顿感。有的节内翻页过渡流畅，但是新节会顿一下

**Comment by 11nk** [comment]
还有个就是目录在阅读中是不是可以跳过不渲染了，好像没什么用。

**Comment by Anxcye** [comment]
> 翻页的体验 感觉不是很统一，有的小说翻页会有卡顿感。有的节内翻页过渡流畅，但是新节会顿一下

是的，切换章节的翻页动画还有问题

> 还有个就是目录在阅读中是不是可以跳过不渲染了，好像没什么用。

目录未来会支持点击跳转到对应页面的功能，那时目录就有用了

**Comment by 11nk** [comment]
> > 翻页的体验 感觉不是很统一，有的小说翻页会有卡顿感。有的节内翻页过渡流畅，但是新节会顿一下
> 
> 是的，切换章节的翻页动画还有问题
> 
> > 还有个就是目录在阅读中是不是可以跳过不渲染了，好像没什么用。
> 
> 目录未来会支持点击跳转到对应页面的功能，那时目录就有用了

有用，但是没那么有用。因为现在目录可以随时点出来，用那个目录 一方面是得跳回到那一页，另一方面这个目录可能还分成很多个页面，不如树状可以折叠的目录好用。

**Comment by Anxcye** [comment]
确实，书里的目录确实不太有用也不够好用，不渲染也影响不大。但是这个目录是书籍文件中的，想要不渲染可能有点麻烦，需要仔细地判断是不是目录，防止跳过一些有用的信息。不过几乎所有书籍的目录也只出现一次，不是很影响阅读。
